/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ppinjamruang;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author dyana
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public MenuUtama() {

        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("Component.focusWidth", 1);
//            UIManager.put("Button.arc", 999);

        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace(); // Bisa juga log atau fallback ke LookAndFeel default
        }

        initComponents();

        // 1. Pastikan JPanel ini opaque agar background-nya digambar
        pDash.setOpaque(true);
        pDash.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15)); // Atas, Kiri, Bawah, Kanan
        pDash.putClientProperty(FlatClientProperties.STYLE, "arc: 15");

        pDash.putClientProperty("JComponent.arc", 15);
        pDash.putClientProperty("JComponent.rounding", 15);

        pDash.setPreferredSize(new Dimension(180, 40)); // contoh ukuran tetap
        bDash.setPreferredSize(new Dimension(74, 20));
        bDash.setOpaque(false);
        pDash.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10)); // atas, kiri, bawah, kanan
        bDash.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0)); // atau sesuai kebutuhan

        //image
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/home.png"));
        Image img = icon.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        lIconD.setIcon(new ImageIcon(img));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pnKanan = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        pDash = new javax.swing.JPanel();
        pLine = new javax.swing.JPanel();
        lIconD = new javax.swing.JLabel();
        bDash = new javax.swing.JLabel();
        pDash3 = new javax.swing.JPanel();
        pLine3 = new javax.swing.JPanel();
        lIconD1 = new javax.swing.JLabel();
        bDash1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pMain = new javax.swing.JPanel();
        pMain1 = new javax.swing.JPanel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnKanan.setBackground(new java.awt.Color(231, 239, 199));
        pnKanan.setLayout(new java.awt.BorderLayout());

        top.setBackground(new java.awt.Color(174, 200, 164));
        top.setPreferredSize(new java.awt.Dimension(600, 60));

        pDash.setBackground(new java.awt.Color(174, 200, 164));
        pDash.setPreferredSize(new java.awt.Dimension(150, 30));
        pDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pDashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pDashMouseEntered(evt);
            }
        });

        pLine.setBackground(new java.awt.Color(174, 200, 164));
        pLine.setPreferredSize(new java.awt.Dimension(5, 28));

        javax.swing.GroupLayout pLineLayout = new javax.swing.GroupLayout(pLine);
        pLine.setLayout(pLineLayout);
        pLineLayout.setHorizontalGroup(
            pLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pLineLayout.setVerticalGroup(
            pLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        lIconD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        lIconD.setPreferredSize(new java.awt.Dimension(20, 20));

        bDash.setBackground(new java.awt.Color(174, 200, 164));
        bDash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bDash.setText("Dashboard");
        bDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bDashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bDashMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pDashLayout = new javax.swing.GroupLayout(pDash);
        pDash.setLayout(pDashLayout);
        pDashLayout.setHorizontalGroup(
            pDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lIconD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(bDash, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pDashLayout.setVerticalGroup(
            pDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDashLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lIconD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pDash3.setBackground(new java.awt.Color(174, 200, 164));
        pDash3.setPreferredSize(new java.awt.Dimension(150, 30));
        pDash3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pDash3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pDash3MouseEntered(evt);
            }
        });

        pLine3.setBackground(new java.awt.Color(174, 200, 164));
        pLine3.setPreferredSize(new java.awt.Dimension(5, 28));

        javax.swing.GroupLayout pLine3Layout = new javax.swing.GroupLayout(pLine3);
        pLine3.setLayout(pLine3Layout);
        pLine3Layout.setHorizontalGroup(
            pLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        pLine3Layout.setVerticalGroup(
            pLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        lIconD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/build.png"))); // NOI18N
        lIconD1.setPreferredSize(new java.awt.Dimension(20, 20));

        bDash1.setBackground(new java.awt.Color(174, 200, 164));
        bDash1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bDash1.setText("Data Ruangan");
        bDash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDash1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bDash1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bDash1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pDash3Layout = new javax.swing.GroupLayout(pDash3);
        pDash3.setLayout(pDash3Layout);
        pDash3Layout.setHorizontalGroup(
            pDash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDash3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lIconD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(bDash1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pDash3Layout.setVerticalGroup(
            pDash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDash3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pDash3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bDash1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lIconD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Pinjam");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("RuangSYS");

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pDash, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pDash3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addGroup(topLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(0, 2, Short.MAX_VALUE))))
                    .addGroup(topLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pDash3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnKanan.add(top, java.awt.BorderLayout.PAGE_START);

        pMain.setBackground(new java.awt.Color(231, 239, 199));

        pMain1.setBackground(new java.awt.Color(231, 239, 199));
        pMain1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnKanan.add(pMain, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnKanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pDashMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pDashMouseEntered

    private void bDashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashMouseEntered
        // TODO add your handling code here:
        pDash.setBackground(new Color(231, 239, 199));
        pLine.setBackground(new Color(138, 120, 78));

    }//GEN-LAST:event_bDashMouseEntered

    private void bDashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashMouseExited
        // TODO add your handling code here:
        pDash.setBackground(new Color(174, 200, 164));
        pLine.setBackground(new Color(174, 200, 164));

    }//GEN-LAST:event_bDashMouseExited

    private void pDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pDashMouseClicked

    }//GEN-LAST:event_pDashMouseClicked

    private void bDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDashMouseClicked

        pDash.setBackground(new Color(231, 239, 199));
        pLine.setBackground(new Color(138, 120, 78));

        pMain1.removeAll();
       pMain1.add(new DashboardPanel()); // ✅ berikan referensi MenuUtama
        pMain1.repaint();
        pMain1.revalidate();
    }//GEN-LAST:event_bDashMouseClicked

    private void bDash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDash1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bDash1MouseClicked

    private void bDash1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDash1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bDash1MouseEntered

    private void bDash1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDash1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_bDash1MouseExited

    private void pDash3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pDash3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pDash3MouseClicked

    private void pDash3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pDash3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pDash3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bDash;
    private javax.swing.JLabel bDash1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lIconD;
    private javax.swing.JLabel lIconD1;
    public javax.swing.JPanel pDash;
    private javax.swing.JPanel pDash1;
    private javax.swing.JPanel pDash2;
    public javax.swing.JPanel pDash3;
    private javax.swing.JPanel pLine;
    private javax.swing.JPanel pLine1;
    private javax.swing.JPanel pLine2;
    private javax.swing.JPanel pLine3;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pMain1;
    private javax.swing.JPanel pnKanan;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables

   

}
